version: "3"

services:
  api-prod:
    build:
      context: .
      args:
        - PORT=${PORT:-9081}
    image: reame-service:prod
    env_file:
    - .env.prod
    restart: always
    network_mode: host