version: "3"

services:
  api:
    build:
      context: .
      args:
        - PORT=${PORT:-9081}
    container_name: "${TAG:-dev}_api"
    restart: always
    network_mode: host
    # ports:
      # - "${HOST:-127.0.0.1}:${PORT:-9081}:8082"